@startuml sequence
activate Alice #ffffff
Alice -> Bob: Authentication Request
activate Bob #ffffff
Bob --> Alice: Authentication Response
deactivate Bob

Alice -> Bob: Another authentication Request
activate Bob #ffffff
Alice <-- Bob: another authentication Response
deactivate Bob
deactivate Alice
@enduml