@startuml singleton
skinparam classFontSize 16

class Singleton {
        
    - {static} instance:Singleton

    + {static} getInstance():Singleton
}
@enduml

@startuml singleton_enum
skinparam classFontSize 16

enum Singleton {
        
    + {Static} INSTANCE

}
@enduml


@startuml observer
skinparam classFontSize 16

abstract class Subject {
    + addObserver(o: Observer)
    + removeObserver(o: Observer)
    # notify()    
}

interface Observer {
    + update()
}

Subject o-> "*" Observer

class ConcreteSubject extends Subject

class ConcreteObserver implements Observer

@enduml

@startuml observer_seq 
hide footbox

actor Observer1
actor Observer2
participant Subject 


Observer1 -> Subject : addObserver
activate Subject
return
Observer2 -> Subject : addObserver
activate Subject
return

activate Client
Subject <- Client : modify
activate Subject
Subject -> Subject : notify
activate Subject

Subject -> Observer1 : update()
activate Observer1
return 

Subject -> Observer2 : update()
activate Observer2
return 

return
return

@enduml

@startuml composite
abstract class Component

class Leaf 
class Composite  
Component <|-- Composite
Component "*" <--o Composite 

Component <|-- Leaf

@enduml

@startuml mediator
skinparam Linetype ortho

interface Mediator {
    + send(target, message)
}

interface Colleague {
    + receive(message)
}



class ConcreteColleague1 extends Colleague
class ConcreteColleague2 extends Colleague

class ConcreteMediator extends Mediator
ConcreteMediator o-> ConcreteColleague1
ConcreteMediator o-> ConcreteColleague2

Mediator <- Colleague

@enduml

@startuml visitor
skinparam Linetype ortho

abstract class Element {
    + accept(v: Visitor)
}
Element <|-- ConcreteElementA 
Element <|-- ConcreteElementB 

interface Visitor {
    + visit(e: Element)
}
Visitor <|-- ConcreteVisitor

Client --> Visitor
Client --> Element

@enduml

@startuml visitor_seq 
    hide footbox


    participant Visitor
    participant Client
    participant ParentElement
    participant ChildElementA
    participant ChildElementB

    activate Visitor
    Visitor -> Client : call(visitor)
    activate Client
    Client -> ParentElement : accept(visitor)
    activate ParentElement
    ParentElement -> Visitor : visit(parentElement)
    activate Visitor
    return
    ParentElement -> ChildElementA : accept(visitor)
    activate ChildElementA
    ChildElementA -> Visitor : visit(childElementA)
    activate Visitor
    return
    return
    ParentElement -> ChildElementB : accept(visitor)
    activate ChildElementB
    ChildElementB -> Visitor : visit(childElementB)
    activate Visitor
    return
    return
    return
    return
@enduml

@startuml strategy
class Context {
    + action()
}

interface Strategy {
    + algorithm()
}
Strategy <|.. StrategyA
Strategy <|.. StrategyB

Context o-> "1" Strategy
@enduml

@startuml state
class Context {
    + action()
}

interface State {
    + handle()
}
State <|.. StateA
State <|.. StateB

Context o-> "1" State
@enduml

@startuml decorator

abstract class Component {
  + operation()
}
class ConcreteComponent {
    + operation()
}
Component <|-- ConcreteComponent
abstract class Decorator {
    + operation()
}
Component <|-- Decorator
Decorator o--> "1" Component


class SuperpowerA extends Decorator {
    + operation()
}

class SuperpowerB extends Decorator {
    + operation()
}

@enduml

@startuml basic_states
hide empty description

state State1
state State2
state State3

@enduml

@startuml basic_states_desc

state State1
state State2
state State3

@enduml

@startuml state_transitions

state Asleep
state Awake

Asleep -> Awake : alarm sounds

Awake -> Asleep : bed time

@enduml


@startuml sandwich_states
state Frozen
state Thawed
state Cooked
state Eaten

[*] -> Frozen

Frozen --> Thawed : defrost
Thawed --> Cooked : cook
Thawed -> Frozen : freeze
Cooked -> Eaten : eat
Eaten -> [*]
@enduml

@startuml monster_states

state Patrolling
state Searching
state Chasing
state Fleeing

[*] -> Patrolling

Patrolling -> Searching : hears player
Searching -> Patrolling : tick [ player.isDead ]

Patrolling --> Chasing : sees player
Searching --> Chasing : sees player
Chasing --> Patrolling : tick [ player.isDead ]
Chasing --> Fleeing : hit [ health < 10 ]
Fleeing -> Patrolling : tick [ distance > 10 ]

@enduml

@startuml monster_scream

state Patrolling
state Searching
state Chasing
state Fleeing

[*] -> Patrolling

Patrolling -> Searching : hears player
Searching -> Patrolling : tick [ player.isDead ]

Patrolling --> Chasing : sees player
Searching --> Chasing : sees player
Chasing --> Patrolling : tick [ player.isDead ]
Chasing --> Fleeing : hit [ health < 10 ] / scream()
Fleeing -> Patrolling : tick [ distance > 10 ]

@enduml

@startuml monster_entry_exit

state Patrolling
state Searching
state Chasing
Chasing : entry / roar()
state Fleeing
Fleeing : entry / scream()
Fleeing : exit / pant()

[*] -> Patrolling

Patrolling -> Searching : hears player
Searching -> Patrolling : tick [ player.isDead ]

Patrolling --> Chasing : sees player
Searching --> Chasing : sees player
Chasing --> Patrolling : tick [ player.isDead ]
Chasing --> Fleeing : hit [ health < 10 ] 
Fleeing -> Patrolling : tick [ distance > 10 ]

@enduml

@startuml monster_compound

state Healthy {
  state Patrolling
  state Searching
  state Chasing
  [*] -> Patrolling

  Patrolling : exit / startle()

  Patrolling -> Searching : hears player
  Searching -> Patrolling : tick [ player.isDead ]

  Patrolling --> Chasing : sees player
  Searching --> Chasing : sees player
  Chasing --> Patrolling : tick [ player.isDead ]
}

[*] -> Healthy

Chasing : entry / roar()
state Fleeing
Fleeing : entry / scream()

Healthy --> Fleeing : hit [ health < 10 ] 
Fleeing -> Healthy : tick [ health > 15 ]

Healthy --> Incapacitated : tick [ health <= 0 ]
Fleeing --> Incapacitated : tick [ health <= 0 ]
Incapacitated -> [*]
state Incapacitated 
Incapacitated : entry / groan()

@enduml